name: Docker Image CI

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Github Container Registry (GCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push - Frontend
        run: |
          docker build . --tag ghcr.io/shanelkapramuditha/ums-frontend:latest
          docker run ghcr.io/shanelkapramuditha/ums-frontend:latest
          docker push ghcr.io/shanelkapramuditha/ums-frontend:latest
        # uses: docker/build-push-action@v4
        # with:
        #   context: ./
        #   file: ./Dockerfile
        #   push: true
        #   # tags: ${{ github.actor }}/ums-frontend:latest
        #   tags: shanelkapramuditha/ums-frontend:latest



# name: Docker Image CI

# on:
#   pull_request:
#     branches:
#       - "main"
#   push:
#     branches:
#       - "main"

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - name: Build and push - Frontend
#         uses: docker/build-push-action@v4
#         with:
#           context: ./
#           file: ./Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/af-frontend:dev
